/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./*.js"],
  safelist: [
    "border-2",
    "border-yellow-300",
    "rounded-xl",
    "p-4",
    "bg-white",
    "shadow-md",
    "flex",
    "flex-col",
    "items-center",
    "w-full",
    "text-left",
    "text-sm",
    "text-xs",
    "text-gray-600",
    "text-gray-500",
    "text-yellow-400",
    "gap-1",
    "gap-2",
    "justify-start",
    "bg-green-300",
    "bg-lime-200",
    "bg-red-200",
    "px-3",
    "py-1",
    "rounded",
    "h-64",
    "object-cover",
    "mb-3",
    "mb-2",
  ],
};
